branches:
    only:
        - master
before_install:
    - npm i -g npm@latest
install:
    - npm install
    - npm run bootstrap
after_script: npm run coveralls
language: node_js
node_js:
    - lts/*  # Most recent LTS version,
    - 14     # Explicitly
    - 10     # Explicitly
#    - node   # Current stable (tests fail with node 15)
sudo: false
env:
    global:
        - NODE_ENV=test
cache:
    npm: true
    directories:
        - 'node_modules'
