[install]
workspaces = true

[test]
pathIgnorePatterns = [
    "packages/libpostal/**",
    "packages/istex/**",
    "packages/sparql/**",
    "packages/xslt/**"
]

coverageThreshold = { lines = 0.8, functions = 0.95, statements = 0.95 }

coverageSkipTestFiles = true

coveragePathIgnorePatterns = [
    "*/*/lib/**",
    "*/*/test/**",
    "packages/transformers/**",
    "packages/conditor/**",
    "packages/istex/**",
]
