{
 "title": "EZS Overview (vptdmservices)",
 "description": "Suivi des flux (ezs) dans les workers ",
 "tags": [ "production" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(nodejs_version_info, instance)"
    }
   },
   {
    "name": "pathName",
    "label": "pathName",
    "query": {
     "query": "label_values(ezs_statement_chunks_total, pathName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Usage counter",
   "type": "timeseries",
   "description": "irate of stream counter",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "irate(ezs_stream_total{instance=~\"$instance\", pathName=~\"$pathName\"}[5m])",
     "legendFormat": "{{instance}}{{pathName}}"
    }
   ]
  },
  {
   "title": "Number of requests",
   "type": "stat",
   "description": "since the last restart of the instance",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum(ezs_stream_total{instance=~\"$instance\",pathName=~\"$pathName\"})\n"
    }
   ]
  },
  {
   "title": "Number of chunks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum(ezs_stream_chunks_count{instance=~\"$instance\",pathName=~\"$pathName\"}) "
    }
   ]
  },
  {
   "title": "Usage Duration ",
   "type": "timeseries",
   "description": "irate of stream duration",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(ezs_stream_duration_ms_count{instance=~\"$instance\", pathName=~\"$pathName\"}[$__interval])",
     "legendFormat": "{{job}}{{pathName}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(http_connection_open)" }
   ]
  },
  {
   "title": "Usage I/O",
   "type": "timeseries",
   "description": "of each entrypoint",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "irate(ezs_stream_chunks_count{instance=~\"$instance\", pathName=~\"$pathName\",bucket=\"output\"}[2m])",
     "legendFormat": "{{job}}{{pathName}}"
    },
    {
     "expr": "-1 * irate(ezs_stream_chunks_count{instance=~\"$instance\", pathName=~\"$pathName\",bucket=\"input\"}[2m])",
     "legendFormat": "{{job}}{{pathName}}"
    }
   ]
  },
  {
   "title": "Number of instances",
   "type": "stat",
   "description": "is the number of distinct containers",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(ezs_stream_total) by (instance))"
    }
   ]
  },
  {
   "title": "Number of entry points",
   "type": "stat",
   "description": "is the number of distinct pathname",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(ezs_stream_total) by (pathName))"
    }
   ]
  },
  {
   "title": "Bytes recevied ",
   "type": "heatmap",
   "description": "Stream buckets' distribution ",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(ezs_stream_size_bytes_bucket{instance=~\"$instance\", pathName=~\"$pathName\",bucket=\"input\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Workers version Usage",
   "type": "barchart",
   "description": "distinct by nodejs version",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 18 },
   "targets": [
    {
     "expr": "count(count(nodejs_version_info) by (job, version)) by (version)"
    }
   ]
  },
  {
   "title": "Objects received",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(ezs_stream_chunks_bucket{instance=~\"$instance\", pathName=~\"$pathName\",bucket=\"input\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "TODO",
   "type": "text",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 30 },
   "options": {
    "content": "Le nombre de requêtes et de chunks reçus par la machine. \n - *TOFIX* : indiquer depuis quand \n - *TODO* : mettre en corrélation avec les requêtes en erreur\n - *TODO* : montrer l'évolution du nombre de requêtes pour montrer les pics de connexion\n\n Mettre en évidence le temps de réponse par requête.\n - *TODO* : corréler le temps de réponse et le nombre de documents traités\n - *TODO* : proposer un histogramme "
   }
  }
 ]
}